name: Run Python Script

on:
  # Adjust this to trigger the workflow as needed:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9:00 AM UTC (adjust as needed)

jobs:
  run-script:
    runs-on: ubuntu-latest  # You can use other runners if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: apartment_project.ipynb  # Replace with your script's name
