name: Daily Scraper

on:
  schedule:
    # Runs daily at 9:00 AM CET (8:00 AM UTC)
    - cron: "40 15 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-22.04

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"  # Adjust as needed

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a `requirements.txt`

      # Run the scraper
      - name: Run scraper
        run: |
          jupyter nbconvert --to notebook --execute apartment_project.ipynb
